### ISSUE TITLE
Implement segregated witness.

### ISSUE THREAD

**Issue by gmaxwell** [bitcoinclassic/bitcoinclassic#185] opened 2016-08-14 21:27 UTC
Historically Bitcoin Classic has fallen far behind on updates to network consensus behavior. It appears to be doing so again.  I noticed that there wasn't even an issue for updating to support segwit.

Segwit is specified in the following documents:

https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0145.mediawiki
and implemented in Bitcoin Core: https://github.com/bitcoin/bitcoin/pull/8149

**Comment by NiKiZe** [comment] 2016-08-14 21:51
The benefits of SW is fewer then the risks, a increase of blocksize limit would be more beneficial for everyone, so merging SW into Classic would just be a wasted effort, and alienate many of it's users.

**Comment by gmaxwell** [comment] 2016-08-15 01:56
Segwit is much more than just a blocksize change. It derisks the increase in several important ways, and fixes a number of important bugs in Bitcoin. Support for segwit appears to be almost universal, and even Bitcoin Classic developers (such as Gavin  have spoken in support of it).

**Comment by FinalHash** [comment] 2016-08-15 04:33
@gmaxwell In general this is not how we would accept an issue tracker. Please resubmit your issue in a more precise way. You have 48 hours to submit a more comprehensive and honed issue tracker or this one will be subject for removal.

Regards

**Comment by gmaxwell** [comment] 2016-08-15 04:44
> @gmaxwell In general this is not how we would accept an issue tracker. Please resubmit your issue in a more precise way. You have 48 hours to submit a more comprehensive and honed issue tracker or this one will be subject for removal.

What specifically are you looking for? I just flipped though all 59 issues ever submitted to the project and am unable to determine any standard for precision being missed here.

**Comment by FinalHash** [comment] 2016-08-15 04:59
> What specifically are you looking for? I just flipped though all 59 issues ever submitted to the project and am unable to determine any standard for precision being missed here.

I would ask that you provide something far more concrete on what you think the issue is. Additionally, how to resolve and issue or at least more specifics on what you see as the problem is common.

**Comment by zander** [comment] 2016-08-15 08:52
Ah, thank you Greg for contributing to our project. Much appreciated.

It is understandable you missed the CONTRIBUTION.md (although a link was shown to you while opening the report, wasn't it?) and you must have missed the roadmap documents (check our documentation repo).

There you will see the SW mentioned and how its too early for us to integrate your work.

The philosophy here is that while there are now 3 different full-clients based on the same codebase, and thus 3 teams, we work together to reach the highest velocity. Stuff I write on this end can be cherry-picked by the other 2 clients after sufficient maturation.  This is similar to how many other bigger project do things. So when SW is mature, don't worry we'll find the code!

Thank you so much, again, for thinking of us. Great to see you have us on your radar.

I'll leave the report open for a while.

**Comment by gmaxwell** [comment] 2016-08-15 09:01
There is no mention of SW in https://github.com/bitcoinclassic/bitcoinclassic/blob/develop/CONTRIBUTING.md  the document does say the development branch takes changes 'optimistically', and I see that it currently incorporates several completely unspecified/undocumented changes to the protocol and network security model. There appears to be no obvious bar for maturity in this projects development branch, at least one is not described in the contributing document.

Based on Bitcoin Classic's track record on prior consensus changes, you are currently very likely to end up inconsistent with consensus again. Avoiding this calls for immediate action to begin implementing BIP141, 143, 144, 145. Can you tell me when you plan to begin this integration work?

**Comment by zander** [comment] 2016-08-15 09:18
Greg, I pointed to two documents.
The CONTRIBUTION.md is about things like; 

> In the Classic project all contributions are valuable and everyone can
> contribute.  Contributions are valued based on how well they fit in the project
> goals and spirit.  It helps to socialize with the Classic people if you are
> unsure what those are.

The roadmap actually talks about SW. Please give it a read :)

**Comment by gmaxwell** [comment] 2016-08-15 09:31
> Greg, I pointed to two documents. The CONTRIBUTION.md is about things like; 

There is no file in the repository called CONTRIBUTION.md. The text you mentioned exists in CONTRIBUTING.md, along with the text about optimistic inclusion.

The word roadmap also occurs nowhere in this repository. I did a google search, but only found a six month old document which only discussed a consensus incompatible "version". Can you tell me when you plan to begin this integration work? -- or provide a hyperlink to a document that does?

**Comment by zander** [comment] 2016-08-15 09:33
I will refer you to my first post,it has all the details you ask for :)

**Comment by rebroad** [comment] 2016-08-25 08:29
@zander I'm also confused and so far have only found the CONTRIBUTING.md document mentioned by @gmaxwell. I am somewhat confused about which bitcoin codebase to support, and believe that a node that can speak both XTHIN and SEGWIT would be beneficial to the entire network.

I don't understand Core's reasons for not including XTHIN as much as I don't understand Classic's reasons for not including SEGWIT.  Perhaps there are good reasons for both decisions, and they might not be the best comparisons to make since not including XTHIN won't risk losing consensus, whereas not including SEGWIT might (although how likely this is is yet to be seen!).

Anyway, egos and politics are probably the answer to my confusion here - I don't think either projects are an appropriate place for these...

**Comment by zander** [comment] 2016-08-25 09:04
@rebroad  Let me quote myself;

> [in the roadmap] you will see the SW mentioned and how its too early for us to integrate your work.

So if you look at the roadmap in our documentation repository you will see the intention that has been there for months that when segwit is done it will be integrated.  Its not nearly done, so its too early to integrate it.

**Comment by dgenr8** [comment] 2016-08-25 13:24
@rebroad Also, the complexity of segwit as a soft fork makes it undesirable given the likely uptake by users.  It is designed to promote off-chain applications which themselves face very uncertain uptake. Segwit is a misstep in the core roadmap that unnecessarily burdens the ecosystem for the scale benefits it brings.

**Comment by zander** [comment] 2016-09-15 16:27
Bitcoin Classic recognizes that github is great at code, not very good as a forum. There are much better places to have discussions and we all agreed in the end about the goals and roadmap being in place wrt segwit.  As such this issue doesn't add anything and I'll close it.

Followup discussion on slack (or similar) please.

**Closed as completed by zander** 2016-09-15 16:27 UTC
