### ISSUE TITLE
Blocks downloading stopped with v1.2.0

### ISSUE THREAD

**Issue by wDraw** [bitcoinclassic/bitcoinclassic#201] opened 2017-01-06 10:49 UTC
I'm not sure whether that is a code problem or just i don't have peers that hold enough blocks, which I doubt is the case. The blocks just stopped coming after block number 308065. Very little network traffic after that. I have 14 active connections. It's been like this for hours now. I'm sorry in advance if it's something stupid.

**Comment by zander** [comment] 2017-01-06 10:54
You may want to take a quick look at the debug file (from gui, there is a button to open it on the help screen).
Also, what happens if you restart the node?

**Comment by wDraw** [comment] 2017-01-06 11:33
I was looking at the debug window, when I opened this issue. When I restarted the node, the same thing happens. 14 active connections. Missing block source. I waited about half an hour, still nothing. I am using Windows 7, I've downloaded the installer from the official website.

Update: even around 2 hours later still no blocks

**Comment by zander** [comment] 2017-01-06 14:02
In the debug window there is a 'Open' button for "debug log file" on the right side.
Can you save and attach the log file?

**Comment by wDraw** [comment] 2017-01-06 14:04
[debug.txt](https://github.com/bitcoinclassic/bitcoinclassic/files/690064/debug.txt)

Here you go.

**Comment by zander** [comment] 2017-01-06 16:23
Nothing in there that indicates the issue.

Could you start your node for about 15 minutes again, but this time passing this command line argument:
`-debug=net`

and then send the new debug.txt here.

Thanks.

**Comment by wDraw** [comment] 2017-01-06 17:22
[debug.txt](https://github.com/bitcoinclassic/bitcoinclassic/files/690424/debug.txt)

**Comment by wDraw** [comment] 2017-01-07 08:45
Ran it today.  Same thing happens.

![wallet](https://cloud.githubusercontent.com/assets/20287696/21740584/5669f472-d4c6-11e6-8866-c1ddbcb8d15e.PNG)

![debugwindow](https://cloud.githubusercontent.com/assets/20287696/21740585/5aa35222-d4c6-11e6-9883-4095f6d87af6.PNG)

![debugwindow2](https://cloud.githubusercontent.com/assets/20287696/21740586/5cb36c78-d4c6-11e6-8b0c-1b7466a42ec3.PNG)

Update: I will try to rebuild the blockchain.

**Comment by wDraw** [comment] 2017-01-09 17:12
After trying to rebuild the blockchain, this happens...

![wtf](https://cloud.githubusercontent.com/assets/20287696/21775607/7a4366fa-d69f-11e6-8d2a-33525779155d.PNG)

![wtf2](https://cloud.githubusercontent.com/assets/20287696/21775612/7c2bbdf0-d69f-11e6-95c5-7de6a581a619.PNG)

![wtf3](https://cloud.githubusercontent.com/assets/20287696/21775617/7d8248b8-d69f-11e6-9c00-18047ad74ad5.PNG)

Update: This thing happens twice now.

**Comment by jamoes** [comment] 2017-01-25 19:45
I looked in the second debug.txt you provided, and it doesn't look like there is anything that indicates what the issue is. Are you still experiencing this problem?

I experienced a similar problem in the past (the blockchain always failed to download at a certain block height), and it turns out I had faulty hardware. I moved the blockchain to a different hard-drive, and the problem went away. Ideally it should be able to better detect (and even recover from) bad hardware, but maybe you could try on a different hard-drive to see if that is actually the issue?

**Comment by zander** [comment] 2017-01-30 09:43
This is most likely indeed caused by hardware issues and that makes it practically impossible to detect and handle by the software.
I'm going to close this error as we have not gotten more reports after a month of release and so I'm confident this is an isolated issue.

Please consider a different hard drive to store your chain on and doing a fresh download of the blockchain.

**Closed as completed by zander** 2017-01-30 09:43 UTC
