### ISSUE TITLE
Control network usage

### ISSUE THREAD

**Issue by jzbz** [bitcoinclassic/bitcoinclassic#80] opened 2016-02-06 06:16 UTC
There had been some discussion of implementing bandwidth throttling in the past (https://github.com/bitcoin/bitcoin/issues/273). This might encourage more individuals to run a full node if they can easily project their maximum bandwidth consumption.

I am also curious to hear any thoughts on whether rate limiting would have any impact in the case of a DDoS attack on a node. Late last year while running Bitcoin XT one of my nodes downloaded 300+ GB of data in a night while not uploading more than it would under normal load, it was not a big deal but I imagine users on slower connections with monthly caps would not be happy.

**Comment by rusty-loy** [comment] 2016-02-06 15:41
I investigated this topic yesterday and found two nice differing implementations.

In XT 0.11D, there is a leaky bucket algorithm that throttles bandwidth based on user options that are configurable through a nice GUI.  https://github.com/bitcoinxt/bitcoinxt/pull/81

In the Core master, there is a new configuration -maxuploadtarget that turns off serving old block data once you reach your quota.  https://github.com/bitcoin/bitcoin/pull/6622

Both implementations are quite good and I'm not exactly sure which direction Classic wants to take.

**Comment by zander** [comment] 2016-02-06 17:04
The XT throttling was there mostly to allow people to continue watching their netflix. It had as a side-effect that you could predict how much it would use if your ISP sets you a limit.

Either way, I have no reason to believe that this new feature would have any effect on a node being targeted for DDOS.

**Comment by jtoomim** [comment] 2016-02-06 18:34
Bandwidth throttling is a bad idea. Artificially limiting your node's bandwidth harms the network by delaying block and transaction propagation. If you want to reduce bandwidth usage, you should reduce the number of peers you connect to. 

I'm interested in a blocks-only mode, though. Most of the bandwidth for running a full node comes from sending and receiving INVs for transactions. Get rid of those, and your bandwidth usage will go way down. Of course, then you're no longer helping with transaction propagation, and you won't notice 0-conf transactions. We could maybe put a toggle button into the GUI to look for unconfirmed transactions for 10 minutes (starting with a getmempool request from a peer) for when people want to check to see if something was pending.

Another way to reduce bandwidth usage while still helping with transaction propagation would be to try to batch INVs. I think INV messages are 127 bytes (including the TCP and ethernet overhead), but only contain 32 bytes of payload. Since you have one INV per tx per peer, and you might have 20 peers, that would be about 2.5 kB per tx per peer just for the INV, plus another 0.4 kB for the tx itself and another 127 bytes for the getdata. As you can see, it's mostly INVs.

If we batched them into groups of 8 txids, we could get 256 bytes of payload into 351 bytes on the wire. That would be about 44 bytes per tx per peer instead of 127, a 65% reduction in traffic.

A half-baked idea: we probably don't need all 32 bytes to determine if we've downloaded the transaction before. We could probably add an option to use shortened versions of the hashes that are trimmed down to maybe 6 bytes, which would be enough to uniquely identify a transaction 99.99% of the time. However, some thought would need to be given to adversarial conditions to make sure that intentional collisions are detected and handled appropriately. A message that includes both of the colliding transactions in their full 32-byte forms would likely suffice.

**Comment by christophebiocca** [comment] 2016-02-08 17:35
> If you want to reduce bandwidth usage, you should reduce the number of peers you connect to.

The problem with `maxconnections` is that an average user would have to manually tweak them to achieve their desired bandwidth limit, with no good way to know when it's good enough. A simple fix would be bandwidth targets that result in decreasing `maxconnections` dynamically whenever they're exceeded.

I also believe historical block transfer to other full peers constitutes the bulk of upload bandwidth (which is the more limited half of the pipe on consumer connections). That's trickier to control without using the nuclear "Don't serve blocks" option, as the bandwidth usage is usually due to just 1 or 2 peers at any given time.

**Comment by jtoomim** [comment] 2016-02-27 11:31
The batching idea I posted 21 days ago is already implemented, but it was broken in 0.11. Once we move to 0.12, net traffic should be better.

The shorthash idea might be workable.

http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-February/012477.html

http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-February/012468.html

**Comment by zander** [comment] 2016-07-06 10:49
Closing this for now as nobody is working on it.

**Closed as completed by zander** 2016-07-06 10:49 UTC
