### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by liranby** [bitcoinclassic/bitcoinclassic#168] opened 2016-05-10 11:01 UTC
i used bitcoin classic
a guy moved me money to my bitcoin and i dont see it
https://blockchain.info/address/1C5HF53wBkuG38BGnY56HjQUDd9uPfgd5w

**Comment by ftrader** [comment] 2016-05-10 11:23
Is your node fully synchronized?
Because the transaction spending to that address was confirmed in block 410862 (288 confirmations by now).

**Comment by liranby** [comment] 2016-05-10 11:28
i dont now. i have node.js 6.1.0 i didnt know that i need to use this soft to make or able to make transfer
can you connect my computer and fix this?
or tell me what to do?

**Comment by ftrader** [comment] 2016-05-10 11:44
how did you obtain the Bitcoin address that the guy sent money to you?
This one: 1C5HF53wBkuG38BGnY56HjQUDd9uPfgd5w

P.S. please don't post any private keys/passwords or any other confidential information here (not that you did yet - just want to warn you to be careful)

**Comment by liranby** [comment] 2016-05-10 11:46
just installed the software and the software gived me and created random adress for my use

**Comment by ftrader** [comment] 2016-05-10 11:51
usually when you install the Classic software, you will have to wait until it has downloaded the blockchain data (the Bitcoin global ledger). This usually takes quite a long time (depending on your Internet connection). You should be able to see the progress in the status bar.
Currently, the blockchain consists of 411151 blocks. (+1 more every 10 minutes on average).
Your money is coming in block 410862 , so until the software has downloaded up to at least that block, it doesn't know that anyone has transferred you that money yet.

I think you just need to wait until the blockchain download is finished, then you should see the funds.

NOTE: the blockchain download will take up a lot of space on your computer (about 74GB currently).
You should also check if you have enough free space, to avoid running out mid-way through :-)

**Comment by liranby** [comment] 2016-05-10 11:56
![default](https://cloud.githubusercontent.com/assets/19284726/15145571/09768042-16bf-11e6-84a5-94a4452d8605.png)
![2](https://cloud.githubusercontent.com/assets/19284726/15145627/669a233c-16bf-11e6-825f-de2025cfc1da.png)
this is what i see

**Comment by liranby** [comment] 2016-05-10 12:06
i dont have 74gb free in c where my bitcoin classic instlled but in e there is 154gb free.
so what to now?

**Comment by ftrader** [comment] 2016-05-10 12:11
I'm pretty sure the little green progress bar at the bottom is indicating that you're still quite some time behind full sync (it's saying 2 years and 45 weeks to go, right?)

P.S. I think you can delete the first screenshot, it's not adding new info.

What to do now?

Either move some other data to E: to free up enough space on C:, or you can decide to move the Bitcoin software data directory.

See e.g. these instructions:
http://bitzuma.com/posts/moving-the-bitcoin-core-data-directory/

**Comment by ftrader** [comment] 2016-05-10 12:24
> can you connect my computer and fix this?

No, you should be very careful about letting people connect to your computer if you have a Bitcoin wallet on there - if they can get access to your private keys they can steal your bitcoins.

You should make at least a backup of the wallet.dat file if you haven't got a backup already, and keep it somewhere safe and secure (not on your computer).

P.S. take care not to destroy that file accidentally (e.g. when moving data), otherwise you could lose your keys and thereby access to your coins.

**Comment by liranby** [comment] 2016-05-10 12:31
ok i backup the file bitcoin.dat and moved the bitcoin software and the database download
whats now?

**Comment by liranby** [comment] 2016-05-10 12:34
how much does it take to download 74gb?

**Comment by ftrader** [comment] 2016-05-10 12:40
wallet.dat is the important file - did you backup the right one?

The time for the initial block sync varies according to the speed of your computer and network connection. Can be as low as a few hours, or a whole day or more if your network connection is slow.

Let it run, have a look that the progress bar keeps moving along, and if it gets stuck, close the Bitcoin software and restart it to resume the sync.

**Comment by liranby** [comment] 2016-05-10 12:44
yes i saved it as bitcoin.dat
but it actully dont take a year right

**Comment by liranby** [comment] 2016-05-10 12:46
"the last stock was made before 2 years and 43 weeks.
transfer that made after this transfer will not shown"

**Comment by ftrader** [comment] 2016-05-10 12:46
> but it actully dont take a year right

No :-) unless it gets stuck and you don't notice for a year :-)

A good source of information is the Bitcoin Wiki, e.g.

https://en.bitcoin.it/wiki/Securing_your_wallet#Windows

There's a lot of useful information there, mostly of course written about Core, but the main features of the software are still the same (in v.0.12).

**Comment by seandotau** [comment] 2016-05-10 22:01
FWIW: Took almost a week for me to download the entire blockchain. It starts off really fast, but towards the end it really slows down.

**Comment by ftrader** [comment] 2016-05-11 07:40
I think it might help a bit, if you have a lot of memory, to set the dbcache parameter to as much as you can afford (2GB+). This will help by avoiding some disk accesses.

**Comment by zander** [comment] 2016-05-24 16:25
Thanks for everyones help, I will close the issue now.

**Closed as completed by zander** 2016-05-24 16:25 UTC
