### ISSUE TITLE
JSON failed to decode GBT solo mining cgminer segmentation fault

### ISSUE THREAD

**Issue by ghost** [bitcoinclassic/bitcoinclassic#259] opened 2017-04-22 19:25 UTC
Getting a core dump from cgminer whilst trying to solo mine with cgminer using antminer USB miners. This happens on cgminer v4.9.0, 4.9.2 and 4.10.0.
Solo mining against BU v1.0.x.x and core v0.12.x is working fine.

 [2017-04-22 20:20:32.822] Started cgminer 4.10.0
 [2017-04-22 20:20:34.343] Probing for an alive pool
 [2017-04-22 20:20:34.390] Pool 0 JSON failed to decode GBT
 [2017-04-22 20:20:34.390] Block change for http://127.0.0.1:31000 detection via
 getblockcount polling./asic: line 7:  3083 Segmentation fault      (core dumped) cgminer -o $url:$port -u $username -p $password --btc-address $address --hotplug 0 --anu-freq 250 --au3-freq 250 --au3-volt 830

**Comment by zander** [comment] 2017-04-22 19:40
Would you be able to share your Bitcoin Classic log file?
Its the debug.log file. You can find it the data dir; http://bitcoinfactswiki.github.io/Data_directory/

**Comment by ghost** [comment] 2017-04-22 19:45
This was the only message I got when attempting to run cgminer:

2017-04-22 19:43:16 CreateNewBlock(): total size 99741 txs: 179 fees: 14829977 sigops 610

**Comment by zander** [comment] 2017-04-22 20:26
Were you mining on mainnet?

**Comment by ghost** [comment] 2017-04-22 20:32
Yes. Chances of winning the lottery with 2 GH/s is rather low! I'd just started the node, so it hadn't had time to fill up with tx's.
I wonder if it relates to some sort of minor GBT version changes.

**Comment by zander** [comment] 2017-08-14 09:04
Can't reproduce, and as the crash is not in Classic. Closing.

**Closed as completed by zander** 2017-08-14 09:04 UTC
Labels: BugFix, Bigger Project
