### ISSUE TITLE
new block download does sometimes stall in v0.12?

### ISSUE THREAD

**Issue by mmouse-** [bitcoinclassic/bitcoinclassic#105] opened 2016-02-25 00:06 UTC
I can't produce a real test case, but I experienced this a few times now during the last days, running v0.12 classic from this git repo.
I have a datacenter internet connection and about 25 peers connected. Enough disk space and 10GB of RAM, about 40% of it free. Normally blocks show up in the printconsole log shortly before/after being visible on blockchain.info.

Block 399886 was mined at about 23:08 UTC. 
It simply doesn't show up in the bitcoind console log of my node. (It got my attention because my p2pool node starts complaining thoroughly about block-stale shares.)
After some minutes of waiting I do a "getpeerinfo" and the "synced_headers" entry of some peers already show this block.
It then takes a full 20 minutes, until first a "Timeout downloading block from peer, disconnecting" occurs and immediately afterwards the new block shows up.

Can anybody confirm/dismiss this problem? I'm a bit lost providing a more solid bug report for this, sorry.

Full printconsole log of my incident: http://pastebin.com/bfRY9e7q

"getpeerinfo" around 23:20 UTC does show the peer in question as:
  {
    "id": 722,
    "addr": "45.59.67.242:48842",
    "services": "0000000000000001",
    "relaytxes": false,
    "lastsend": 1456355777,
    "lastrecv": 1456355778,
    "bytessent": 5956,
    "bytesrecv": 3964,
    "conntime": 1456350375,
    "timeoffset": -67218,
    "pingtime": 0.125517,
    "minping": 0.125333,
    "version": 70002,
    "subver": "/Satoshi:0.11.2/",
    "inbound": true,
    "startingheight": 398961,
    "banscore": 0,
    "synced_headers": 399886,
    "synced_blocks": 399885,
    "inflight": [
    ],
    "whitelisted": false
  },

**Comment by zander** [comment] 2016-02-25 08:58
I can confirm.

**Comment by jtoomim** [comment] 2016-02-29 23:48
If a peer is malicious, improperly configured, or behind a poor internet connection, it can offer to send a block but simply refuse to do so. This will tie up the download slot by marking the block as "in flight", which will prevent you from trying to download it from another peer.

One way of dealing with instances like this is to reduce the timeout, or to make the timeout more intelligent vis-a-vis blocks that are downloading, but going slowly. 

Having a block download timeout should probably result in a peer ban.

Blocktorrent and dagurval's thin blocks are resistant to this type of issue, since they download from multiple peers in parallel. I don't know about XTB.

In any case, @mmouse- if you're mining, you should be running the relay network client. That will give you a second parallel path for receiving new blocks and make it less likely for issues like this (which should still be fixed!) from causing you to lose revenue.

**Comment by FinalHash** [comment] 2016-03-01 05:57
Are you getting the same issues on Core 12? I feel like I remember them chopping down some logging. Maybe I dreamed that.

**Comment by mmouse-** [comment] 2016-03-03 12:07
@jtoomim The block wasn't marked as "in flight" in getpeerinfo...
And thanks for the hint to relay network. No serious mining here, it's more playing around. But I'll see if I give it a try, just out of curiosity.

@FinalHash I didn't use Core 12, but there is an almost identical, more verbose bugreport at https://github.com/bitcoin/bitcoin/issues/7596

**Comment by zander** [comment] 2016-03-24 13:12
Closing for now as "can't reproduce" Feel free to comment if this happens again.

**Closed as completed by zander** 2016-03-24 13:12 UTC
